all: $(EXE) lumps

LUMPSRC=workbench/lumps
LUMPDST=data/lumps

$(LUMPDST)/%.lump.lua: $(LUMPSRC)/%.blend tools/exporters/export_lump.py
	./tools/exporters/export_lump.sh $< $@
lumps: $(patsubst $(LUMPSRC)/%.blend, $(LUMPDST)/%.lump.lua, $(wildcard $(LUMPSRC)/*.blend))

a.o: a.c
	$(CC) $(CFLAGS) -c a.c

main.o: main.c mat.h
	$(CC) $(CFLAGS) -c main.c

$(EXE): main.o a.o
	$(CC) main.o a.o -o $(EXE) $(LINK)

clean:
	rm -rf *.o $(EXE) $(LUMPDST)/*.lump.lua

